name: The Whitelister
author: Lolmewn
version: 3.1
main: nl.lolmewn.twl.Main
commands:
  wl:
    description: The Main whitelist command
    usage: /<command> for all whitelister commands
    aliases: [whitelister, whitelist]